### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by Serhii-Hrynyshyn**

### CODE REVIEW

**Review by Bohdan-Salamakha — CHANGES_REQUESTED** [review]
fix it...
image

**Comment by Serhii-Hrynyshyn** [comment]
> fix it... image


how can i fix it i don't understand my problem(? all test an flake8 is confirmed

**Review by YukihiroSM — CHANGES_REQUESTED** [review]
Looks like these symbols are representing spaces and break lines. Try to rewrite the code, because it's not readable. Also, you can try replacing all break lines.

**Review by Bohdan-Salamakha — CHANGES_REQUESTED** [review]
U didn't commit anything new.
Rewrite the code in human-readeble form

**Comment by Serhii-Hrynyshyn** [comment]
this problem i can see only after pull request, on my computer, local its all rights

**Comment by Serhii-Hrynyshyn** [comment]
what can i do to repaire this file?

**Comment by Serhii-Hrynyshyn** [comment]
image

**Review by ArsenPidhoretskyi — CHANGES_REQUESTED** [review]
???? 
image

**Pull request closed without merging**
